module.exports = {
  DEFAULT_FPS: 30,
  DEFAULT_WIDTH: 1920,
  DEFAULT_HEIGHT: 1080,
  DEFAULT_VALIDATION_MODE: "warn",

  // Text batching
  DEFAULT_TEXT_MAX_NODES_PER_PASS: 75,
  INTERMEDIATE_VIDEO_CODEC: "libx264",
  INTERMEDIATE_CRF: 18,
  INTERMEDIATE_PRESET: "veryfast",

  // Encoding
  VIDEO_CODEC: "libx264",
  VIDEO_CRF: 23,
  VIDEO_PRESET: "medium",
  AUDIO_CODEC: "aac",
  AUDIO_BITRATE: "192k",

  // Fonts/Text
  DEFAULT_FONT_FAMILY: "Sans",
  DEFAULT_FONT_SIZE: 48,
  DEFAULT_FONT_COLOR: "#FFFFFF",
  DEFAULT_TEXT_ANIM_IN: 0.25,

  // Audio
  DEFAULT_BGM_VOLUME: 0.2,

  // Transitions
  DEFAULT_TRANSITION_DURATION: 0.5,
};
